### ISSUE TITLE
GIVfi v1

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/Roadmap#36]
This is an epic to assemble all the tasks and subtasks for the GIVfi series of smart contracts. Including:
- Research on capital deployment strategies
- Implementation and improvement of donation handler
      - Enable "cart of projects' functionality into donation handler
- Contract architecture to deploy idle donation funds into strategies on mainnet
- Contract architecture to deploy idle donation funds into strategies on gnosis chain
- GIVsavings - Allow projects to lock funds into GIVfi for a guaranteed yield
- possible modularity improvements or implementation from gitcoin grants protocol

**Comment by KurtMerbeth** [comment]
> I made a [PR](https://github.com/Giveth/GIVfi-donation-handler/pull/11) and added Multicall capability to GIVfiDonationHandler, Kurt reviewed and merged. That enables the user to call multiple methods (multiple donate) in single transactions. So we would be able to donate to multiple project by that, but not much gas efficient!

true, let us think about something more gas efficient

**Comment by divine-comedian** [comment]
@KurtMerbeth @aminlatifi 

What about a donateMultiple function - it could accept three arrays - [tokens][amounts][recipients]

I'm not sure if there's any magic that needs to be done to check user balances for multiple tokens and amounts from a single call

**Comment by divine-comedian** [comment]
Do we need to have the vault always connected to the donation handler?
- maybe we could make it point to a different vault if we have to

**Comment by divine-comedian** [comment]
Plan for this week: 

keep pushing gitcoin, join their calls

how would this look like on the dapp? 

how would we show projects that they need to claim funds?
- [ ] introduce idea to mosaeed

**Comment by divine-comedian** [comment]
- default donations
- updates from kurt
- moving call time 

-----
# kurt updates
- not really any updates
- met with kevin from gitcoin
- will talk with andrea next week - tech lead 
- talk about working for gitcoin
- ask andrea questions about project registry etc..
- donateMany function has already been implemented in donationHandler

- could use disperse app to get cart function out early ahead of using donationHandler
- disperse app is available on all chains but can only disperse 1 type of token at a time
- generate tx for each type of token donated

# default donations 
- check with ramin to see if it's on staging 
- check with moenick for release schedule 

# balancer managed pools
- griff deep dived w/ fabio and gooddollar
- be able to have a variety of strategies and have people managing different portions of portfolio
- https://docs.balancer.fi/products/balancer-pools/managed-pools
- need to research architecture and how it could fit into givfi
- it is live now but doesn't have all the features
- working with index coop to build smart contract controllers

# call time 
- move to biweekly
- no objections
- next call would be for the 24th november

# gitcoin is launching on fantom
- might be interesting to see what happens
- try to participate
- fantom is still testing - want to do full launch for ethdenver

**Comment by divine-comedian** [comment]
## GIVfi call 24 nov 2022
check in
- mitch - hear any updates with coordination with gitcoin  / back to back calls 
- kurt - if we can build something on top of gitcoin what is the feasibility / sitting on a weird chair/desk situation
- lauren - here to stay in the loop
- griff - here ti listen in 

## gitcoin coordination and building 
- talked to andrea who is some sort of tech lead for grant hub
- talked about integrating some sort of donation handler - they don't have a white list currently but have an issue to build something

## building GIVfi
- donation handler has 2 parts - receiving storing donaitons, whitelist for donors and recipients
- shouldn't implement something with token, donor and project whitelist for now - we should wait for this part
- we can build something now for just receiving and storing donations
- can also start the vault contract behind this and yield strategies
- should wait for gitcoin to build whitelist before implementing this part
- make contract upgradeable 
- using an ipfs document isn't safe - anyone can add a project with some data - could add wrong addresses and can't check on smart contract level
- gitcoin can take care of their own verification process on their backend but we don't have that for giveth yet
- they may have launched on fantom already but can't find clear information 
- no problem with using the giveth backend for receiving and disbursing donations
- using contracts from rari capital 

- vault contract holds funds - when user withdraws they withdraw from vault into donation handler instead directly from strategy
- vault or somewallet holds 10% of total funding held - need minimum threshold? 10% held in $oneGIV for users to withdraw 
----
### things to follow up on for next call

@KurtMerbeth 
- [ ] can build donation handler removing whitelist functions and data out of contract - add hooks to implement back quickly or gitcoin compatible 
- [ ] yield strategies research 
- [ ] nothing done yet for vault - think of $oneGIV implementation - how to manage the funds overall 

@GriffGreen 
- [ ] - do session with mitch and lauren to show why it could be critical to keep it in float - want to distract kurt with praise build stuff

@divine-comedian 
- [ ] do more strategy research for both chains participate in $oneGIV

**Comment by divine-comedian** [comment]
# GIVfi Call Dec 8 2022

### check-ins 
- mitch - facilitate this call and figure out where to move forward // hunger 
- kurt - here because they see more problems than solutions for whitelisting // babysitting on the side 
- cotabe - sync up regarding GIVdowments 

## whitelist for projects
- gitcoin doesn't consider project whitelist - can't find a way to build it on top of the protocol
- protoocl has grant round - project can apply for grant round, factory is built by gitcoin, we can't change it
- we could build our own whitelist contract but we allow or disallow projects to participate in grant round 
- could end up with inconsistent data - we allow project but don't whitelist address, recipient addresses are saved on ipfs, project updates address but we have to update ipfs and front-end 
- create your own grant program - project can apply for own grant 
- we want a never ending round that projects can apply for 
- would integrate registry but we would need to build something that relates with it
- we would have to change things in the round factory to make it work for us

### Gitcoin coordination
- changing the round factory
- have a front-end to test the round factory
- do we want to use staging server for test data
- kurt is working full time for Gitcoin
- working mostly on grants hub

### Building GIVfi
- Building smart contract system for Giveth - Making and receiving donations - building in GIVfi, having ipfs registry of verified projects. Allowing future projects like GURVES to plug into it. 
- donation handler seems clear
- vault "cold wallet"
- strategy implementation 
- third party fund managers?
- fork round factory 
- merging round handler to donation handler using the never-ending round concept

### Defining Scope - MVP - not audited just to figure out how it works
- Donation Handler that can receive and allow projects to claim donations 
- can accept one whitelisted token
- deposit token into a yield bearing strategy
- remove token from strategy - transfer to donation handler or directly from the vault  
- potentially have a float - % or flat amount of funds in vault not deployed in strategy users could withdraw directly from this float 

### Strategies? 
- create a test MVP deployment on gnosis chain
 OR 
- see if there is any test strategies on goerli 
- find 1 or 2 strategies for testing the mvp deployment

## Things to do 
-  keep call bi-weekly 
- [ ] round factory @KurtMerbeth 
- [ ] find strategies to test goerli & gnosis chain @GriffGreen @divine-comedian 
- [ ] vault and strategies logic & contract needs to be done @KurtMerbeth 
- [ ] @KurtMerbeth try to get in touch with michelle - person in charge of building projects hub lead - michelle is PM but working on grants hub but not projects registry hub. see if there is any requirements we need to know to of to make it compatible with what Giveth is building.


## Sugoi protocol 
 - met person at eth global - working on something similar to GIVdowments  - Green savings Protocol - https://gitcoin.co/grants/7646/sugoi-protocol-web3s-first-green-savings-protocol
 - very ealy stage 
 - need to investigate and see if there is a way to join forces... maybe 
 - @Cotabe will ask and get us more info on the protocol - maybe schedule a call with them to explore if it looks like a good fit.

**Comment by divine-comedian** [comment]
# GIVfi Dec 22, 2022

### From Kurt: 
> I introduced a new role to the Round contract. I assign a projectManager(maybe i should think about another name) address to every project which applies.
the project manager can set a new address if wanted.
instead of having addresses in donationhandler i changed it to the project id
only the project manager is now allowed to withdraw from donationhandler
>
> using the projectIds in donation handler and having the project manager which is changeable and allowed to withdraw, is in my eyes the best solution to connect the contracts. (tbd, you may have objections, let me know)
>
> but there is one prob: basically everyone is allowed to apply with any project id. since there is no connection between the project registry and round contract. - it's also not possible to connect them, since the project registry is multichain and every project from every chain can apply to rounds across chains.
so i will add another function, to acceptProjects and i need to handle assigning the projectmanager there somehow (basically whitelisting of project and projectmanager).
But thats something i will think about the days after christmas

---

we could have a middle registry that cherry picks from the global registry - the middle registry becomes our giveth registry of projects that can join the giveth round manager.

---

GIVfi as a basic principle seems sketchy - using user funds to generate defi yield

don't move user funds from the float unless they opt-in (GIVsavings or GIVdowments)

**Comment by divine-comedian** [comment]
# GIVfi Jan 5, 2023

## Kurt's updates
- had to go back to original donation handler, still need to find a way we can whitelist the address of a project - since the project is multichain it becomes very complicated - giveth needs to handle whitelisting, there was no way to control who applies for the round.
- made progress - rewrote round manger front-end, added factory for donation handler, deployed subgraph for factory, able to deploy a new round with donation handler. replaced voting contract in system for donation handler - keep this familiar to the current gitcoin structure for deploying rounds.
- keep things like how gitcoin does it for smart contract deployment
- talked to someone from round manager, everything is connected with each other (contracts), if it isn't indexed by subgraph it doesn't show up.

- griff hates the gitcoin round manager UI
- need to find a way to build our UI into the grants system
- round team wants to implement multiple voting strategies into system in next month

## QF Research <> GIVfi <> Grants 2.0 . . . 
  
- owocki wants to give us money to integrate grants 2.0 into giveth
- how to use giveth UI to do QF round
- biggest problem is sub-graph issues
- all contracts and queries are connected on a sub-graph
- kurt is not familiar with sub-graph
- carlos, mohammad, amin are familiar with subgraph
- donation handler and GIVfi stuff should be compatible  
    
- cart of projects feature already in donation handler
- users can donate to many projects with less txs
- but we have no UI for this on Giveth
- gitcoin will make big revisions to codebase after the alpha rounds close, including smart contract changes
- best solution is to make a project on gitcoin - if you use current giveth project it doesn't work with sub-graph and indexing 
- we need to add projects to project registry  
    
- can use global registry then pick which projects we want to include in a time-boxed registry
- anyone could add a project to global registry with any information, then apply for round, round operator needs to check for project validity
- can use gitcoin passport for both projects and donors - round operator can see badges when checking projects  


- when we build stuff in the future the legos can stack together

**Comment by divine-comedian** [comment]
Current working draft for mvp spec - still in progress!! 

https://www.notion.so/giveth/GIVfi-MVP-spec-67056e861ae74ae88b01cf42f69569f3

**Comment by divine-comedian** [comment]
## Call note Feb 2

We don't have the money to audit a lot of new contracts - donationHandler makes sense but we should try to find a grants program that will pay us to their contracts

Kurt knows a German company that will audit the code if its for-good 

need to find suitable contracts for 
- Vaults
- GIVdowments

could use rari finance vaults that has a lot of the fees and floating balances - connects to strategies 


### intents and distracts
mitch - amin and kurt to look at the mvp and talk to each other - get amin's input // back to back calls // change call time!!!
amin - looked at givfi spec and added some comments // tired and late 
kurt - no specific intentions // see what's going on// very exhausted and hungry 
lauren - listen in and see what we're moving forward, check in to merging the call with GIVeconomy development 

## Amin's comments on MVP
- understand how much Giveth gets from yield ratio 
- have to figure out withdraw - if they withdraw just a small amount does it make sense to reset yield ratio

- MVP have just a fixed fee 
- fixed fee must be lower than max fee post MVP
- yield ratio in post MVP

### GIVdowments
- no incentive system for investors 
- what if someone deploys a contract
- double charge - we already take a cut from when a project withdraws 
- need to have a way to check that the GIVdowment was deployed using our version 

- we can skip gas costs and save them in browser - so it's not calculated on-chain 
- save the distribution parameters on the browser and generate the txs when disbursing
- depends on implementation later 

- kurt's idea was to have one vault for givdowments and savings - could delegate funds to another user or project
- need to figure out who holds the vault tokens - is it held by the investor or by the givdowment - transferable? non-transferable? 

### MVP GIVsavings suggestions 
- for MVP - deploy vault and attach it to the front-end with just one strategy 
- fixed fee for giveth 
- can only deposit one type of asset - probably better to have a stablecoin 
- only would need an audit for strategy or if we find an out of the box solution we can avoid an audit

### post-MVP GIVsavings 
- multiple vaults 
- multiple stategies 
- donation handler forwarding donations into vaults
- dynamic yield ratio
- donation handler will need an audit 
- vault - with the dynamic yield ratio will and audit 

MVP GIVdowments - look at how post-MVP GIVsavings works 

Kurt is very excited to use yearn or Balancer managed pools and add in the public goods router. 

- need to overhaul the donation handler to match MVP 
- could use GIVfarm designs for depositing - need to connect it to users that have projects 
- idea is that users deposit the funds themselves 

- this would be less complicated to audit - more similar to rari vault 

## moving call time 

- let's check it out in a couple weeks - we used the whole hour 

wednesdays berlin 3pm time 

move it to the top of the GIVeconomy dev call - 3-30pm wednesdays 


-------

- redesign donation handler - something for later 
- find a first MVP strategy 
- check out grants for Balancer
- using rari vault or balancer managed pools for vault contract 
- amin & kurt looking into strategy contracts 
- see if there is a better vault than the rari vault 
- pooltogether doesn't have a real vault - doesn't use ERC-4626

**Comment by divine-comedian** [comment]
## GIVfi Feb 16 2023

mitch - talk about research and grants, protocols
kurt - basically the same 
giantkin - basically the same 

-----
- Mitch is in touch with Beefy and Yearn directly specifically GIVfi and Public Goods Router 
- Beefy hates charities and non-profits
- Yearn - mitch is in touch with their partnerships person 

- still need strategy for yearn strategies 
- since we are not trying to develop a new smart contract we need to find one that works and what's best for us. 

- we have a strategy that deposits into their vault and uses their strategies 
- yearn vaults call their harvests arbitrarily - could lead to problems
- if users pull funds before a harvest they miss the yield entirely 
- check into which yearn vaults call harvest very often - usually the ones with the highest TVL
- using an MVP of a vault of vaults 

-----
https://docs.timelessfi.com/docs/concepts/yield-tokenization

- separates yield and principal into two tokens 

----
current contracts is that they are very big and have more features than what they need - because of this we want to go with rari capital because the contract is very simple 
https://github.com/Rari-Capital/vaults/blob/main/src/Vault.sol
- use this code as is and just connect a strategy to it 
- check this code is well audited and secure 
- https://github.com/Rari-Capital/vaults/tree/main/audits
- the strategy being a yield provider 
- ideally returns yield in same deposit asset 

- mitch will keep looking for grants and fundraising opportunities 
- kurt will keep looking into audits and hack info 


next call during ETH Denver - so we will schedule next GIVfi call on 16 of March

**Comment by divine-comedian** [comment]
## GIVfi Mar 16 2023
Intentions and distractions 
- mitch - look at the MVP contracts kurt deployed on FTM and chat with fundPG and what you're interested | hunger 
- kurt - talk about element fi contracts 
- griff - hear about new contracts! 
- brichis - curious about GIVfi, seems more interesting! | have messages to answer 
- lauren - here to listen! 
- jolow - see what you guys are up to and how he can help! from fundPG, won public goods track at ETH Denver, building no loss donation pool. smart contract developer.

- Element Finance - MVP 
- fits for MVP - deployed on FTM 
- only allows one vault puts it inside wrapped vault 
- gives a wrapped vault token to project owner
- added a fixed withdrawal fee and deployed on FTM using a yearn vault 
- the logic for changing the withdrawal fee needs to be reviewed
- fee is added on withdrawal 
- the fee should be levied on their interest not on the whole balance 

- solution for fundPG - only allowed to deposit once and withdraw once 
- only allow additional deposits? off-chain calculation with an oracle? 
- very easy to apply fee on just yield even with mutliple deposits says Kurt 
- yearn is already doing it - it is already part of ERC-4626 - over every deposit all the time they calculate a yield token they get back every time
- for GIVdaoments - that will be more complicated
- set a cap on GIVdaoment recipient to 5 or something 
- check with requirements for a grant proposal or bounty to build it more

we can use element finance contracts for GIVsavings MVP 
if we can use an out of the box contract and deploy it - with just a few lines of code added we can squeeze some friends for an audit of it.
spearBit DAO of auditors - auditing DAO - could contact them to do auditing for public good 

- @KurtMerbeth will work on building out the fee structure for GIVsavings - taking only out of the yield 
- poolTogether hyperstructure - https://gov.pooltogether.com/t/the-pooltogether-prize-savings-hyperstructure/2753
- @jolow99 - provide links for audit DAOs he knows of. 
- @divine-comedian keep working on finding audit grants or ecosystem grants - follow up @Tosinolawale  for UX design

move up to weekly
